---
functional:
  - Требование 1 Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Требование 2 Пользователь должен иметь возможность фильтровать товары
  - Требование 3 Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Требование 4 Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Требование 5 Сайт должен быть доступен на различных устройствах
  - Требование 6 Сайт должен иметь мобильную версию
non-functional:
  - Требование 7 Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Требование 8 Сайт должен быть безопасным и защищать данные пользователя
  - Требование 9 Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Требование 10 Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Требование 11 Сайт должен иметь платежный модуль
  - Требование 12 Сайт должен использовать файлы Cookie
  - Требование 13 Сайт должен иметь форму регистрации
  - Требование 14 Сайт должен иметь форму авторизации
  - Требование 15 Оформление заказа доступно только авторизированному пользователю
  - Требование 16 В форме регистрации должны присутствовать контактные данные пользователя
  - Требование 17 
  - Требование 18





  
