---
functional:
  - Требование 1 Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Требование 2 Пользователь должен иметь возможность фильтровать товары
  - Требование 3 Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Требование 4 Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Требование 5 Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Требование 6 Пользователь должен иметь возможность на странице корзины удалить товар из корзины
  - Требование 7 Пользователь должен иметь возможность переходить со страницы корзины в каталог
  - Требование 8 Описание товара на странице товара и в каталоге должно содержать название, рейтинг, цену со скидкой и без нее
  - Требование 9 Корзина будет храниться в сессии браузера  
non-functional:
  - Требование 10 Сайт должен быть доступен на различных устройствах
  - Требование 11 Сайт должен иметь мобильную версию
  - Требование 12 Сайт должен быть кроссбраузерным
  - Требование 13 Сайт должен быть безопасным и защищать данные пользователя
  - Требование 14 Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Требование 15 Сайт должен быть нагрузоустойчивым
  - Требование 16 Сайт должен быть SPA-приложением
implicit:
  - Требование 17 Сайт должен иметь платежный модуль
  - Требование 18 Сайт должен иметь форму регистрации
  - Требование 19 Сайт должен иметь форму авторизации
  - Требование 20 Оформление заказа должно быть доступно только авторизированному пользователю
  - Требование 21 В форме регистрации должны присутствовать контактные данные пользователя
  - Требование 23 Форма заказа должна содержать подробную информацию о составе и номере заказа, контактных данных пользователя, адресе и сроке доставки.
  - Требование 24 Корзина должна содержать информацию о всех добавленных товарах и их количестве
  - Требование 25 В корзине должна быть возможность не только удалять товар, но и изменять его количество
  - Требование 26 Должна быть страница просмотра заказов
  - Требование 27 Локализация должна осуществляться в зависимости от пользователя
  - Требование 28 Стоимость товаров должна быть выражена в валюте в зависимости от страны пользователя





  
